### ISSUE TITLE
Compiler Failing because of implicit declarations 

### ISSUE THREAD

**Issue by SirSharpest** [bentley/rgbds#92]
Getting this as an output of make
```
src/gfx/png.c:166:2: error: implicit declaration of function 'png_set_quantize'
      is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        png_set_quantize(img->png, palette, colors, colors, NULL, 1);
```

**Comment by SirSharpest** [comment]
This is with using Clang, I should probably add.

**Comment by SirSharpest** [comment]
Tried with gcc, was able to build with the release 0.24 version however, not sure what the issue is then.

**Comment by bentley** [comment]
What version of libpng are you using?

**Comment by SirSharpest** [comment]
I've tried with a few different versions, I've tried, libpng3, libpng12, libpng16, same error each time. But I was able to make and install [This version](https://github.com/bentley/rgbds/releases/download/v0.2.4/rgbds-0.2.4.tar.gz) without any issues. Has something major changed?

**Comment by bentley** [comment]
Well, the obvious change since 0.2.4 is that there’s now a program that actually uses libpng, `rgbgfx`.

**Comment by bentley** [comment]
What operating system are you using?

`rgbgfx` builds fine here with clang and libpng-1.6.25. You should definitely be using 1.6.something—`rgbgfx` uses libpng APIs from that version.

**Comment by SirSharpest** [comment]
I'm on Ubuntu Linux 16.04.

Ill double check and get back to you with full versions and compiler output

**Comment by yenatch** [comment]
#94

**Comment by lancekindle** [comment]
I also just ran into this error and fixed it by installing the [latest 1.6 version of libpng from sourceforge](https://sourceforge.net/projects/libpng/files/libpng16/).

Xubuntu 16.04 (and consequently Ubuntu 16.04) uses libpng 1.2.54 so we must install libpng from source.
Even installing libpng-dev does not install a newer version (perhaps that's obvious to more experienced people unlike myself)

**Comment by bentley** [comment]
Right, this can be solved by installing a current libpng (too bad they keep “improving” the API all the time). Not related to #94 either.

**Comment by lancekindle** [comment]
I honestly wouldn't have thought to install the newer version of libpng if it weren't for this issue.
Is there anyway we can make checks during the make process?
pkg-config --modversion libpng
will return the version of libpng

**Comment by frarees** [comment]
I hope I'm not bothering anyone writing in a closed issue, but #104 addresses the issue stated by @SirSharpest, grating compatibility with older libpng versions.
